name: Tests and Checks

on: [push, pull_request]

jobs:
  checks:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: 'script -q -e -c "bash {0}"'
    env:
      PY_COLORS: "1"
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", pypy-3.9]
        os: ["macos-latest", "ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout pull request HEAD commit instead of merge commit

      - name: git config before removal
        run: |
          git config --list
          echo -----------------------------

      # Because gitlint is a tool that uses git itself under the hood, we remove git tracking from the checked out
      # code by temporarily renaming the .git directory.
      # This is to ensure that the tests don't have a dependency on the version control of gitlint itself.
      - name: Temporarily remove git version control from code
        run: mv .git ._git

      - name: Setup python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      # - name: printenv
      #   run: |
      #     printenv

      # - name: Unit Tests
      #   run: ./run_tests.sh

      # Coveralls integration doesn't properly work at this point, also see below
      # - name: Coveralls
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      #   run: coveralls

      - name: git config
        run: |
          git config --list
          echo -----------------------------
          git config --global color.ui true
          git config --global color.interactive true

      # - name: gitlint issue298
      #   run: gitlint issue298

      # - name: gitlint issue298 (TTY tried to attach)
      #   shell: 'script -q -e -c "bash {0}"'
      #   run: |
      #     gitlint issue298

      # - name: test issue298
      #   run: |
      #     GITLINT_BIN=$(which gitlint)
      #     gitlint(){
      #       script -q -e -c "$GITLINT_BIN --version"
      #     }
      #     ./run_tests.sh -i  qa/test_issue298.py

      #   env:
      #     TERM: xterm-color
      #   continue-on-error: true # Known to fail at this point

      - name: Patch commit-msg hook
        run: |
          # Escape "$1" to \"$1\"
          sed -i -E '/^gitlint/ s/("\$1")/\\\1\\/' gitlint-core/gitlint/files/commit-msg
          # Replace `gitlint <args>` with `script -e -q -c "gitlint <args>"`
          sed -i -E 's/^gitlint(.*)/script -e -q -c  "\0"/' gitlint-core/gitlint/files/commit-msg
        continue-on-error: true

      # - name: running commit-msg directly
      #   shell: 'script -q -e -c "bash {0}"'
      #   run: |
      #     chmod +x gitlint-core/gitlint/files/commit-msg
      #     cat gitlint-core/gitlint/files/commit-msg
      #   continue-on-error: true

      # - name: running colorama test
      #   run: |
      #     python colors.py
      #   continue-on-error: true

      # - name: running indirect test
      #   shell: 'script -q -e -c "bash {0}"'
      #   run: |
      #     chmod +x ./indirect.sh
      #     ./indirect.sh
      #   continue-on-error: true

      # - name: test issue298 (GITLINT_QA_USE_SH_LIB=0)
      #   env:
      #     GITLINT_QA_USE_SH_LIB: 0
      #   run: ./run_tests.sh -i  qa/test_issue298.py
      #   continue-on-error: true # Known to fail at this point

      - name: Integration Tests
        shell: 'script -q -e -c "bash {0}"'
        run: ./run_tests.sh -i

      - name: Integration Tests (GITLINT_USE_SH_LIB=0)
        env:
          GITLINT_USE_SH_LIB: 0
        run: ./run_tests.sh -i

      - name: PEP8
        run: ./run_tests.sh -p

      - name: PyLint
        run: ./run_tests.sh -l

      - name: Build tests
        run: ./run_tests.sh --build

      # Coveralls GH Action currently doesn't support current non-LCOV reporting format
      # For now,  still using Travis for unit test coverage reporting
      # https://github.com/coverallsapp/github-action/issues/30
      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      # Re-add git version control so we can run gitlint on itself.
      - name: Re-add git version control to code
        run: mv ._git .git

      # Run gitlint. Skip during PR runs, since PR commit messages are transient and usually full of gitlint violations.
      # PRs get squashed and get a proper commit message during merge.
      - name: Gitlint check
        run: ./run_tests.sh -g --debug
        if: ${{ github.event_name	!= 'pull_request' }}

  windows-checks:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout pull request HEAD commit instead of merge commit

      # Because gitlint is a tool that uses git itself under the hood, we remove git tracking from the checked out
      # code by temporarily renaming the .git directory.
      # This is to ensure that the tests don't have a dependency on the version control of gitlint itself.
      - name: Temporarily remove git version control from code
        run: Rename-Item .git ._git

      - name: Setup python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Upgrade pip on Python 3"
        if: matrix.python-version == '3.6'
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: gitlint --version
        run: gitlint --version

      - name: Tests (sanity)
        run: tools\windows\run_tests.bat "gitlint-core\gitlint\tests\cli\test_cli.py::CLITests::test_lint"

      - name: Tests (ignore cli\*)
        run: pytest --ignore gitlint-core\gitlint\tests\cli -rw -s gitlint-core

      - name: Tests (test_cli.py only - continue-on-error:true)
        run: tools\windows\run_tests.bat "gitlint-core\gitlint\tests\cli\test_cli.py"
        continue-on-error: true # Known to fail at this point

      - name: Tests (all - continue-on-error:true)
        run: tools\windows\run_tests.bat
        continue-on-error: true # Known to fail at this point

      - name: Integration tests (continue-on-error:true)
        run: pytest -rw -s qa
        continue-on-error: true # Known to fail at this point

      - name: PEP8
        run: flake8 gitlint-core qa examples

      - name: PyLint
        run: pylint gitlint-core\gitlint qa --rcfile=".pylintrc" -r n

      # Re-add git version control so we can run gitlint on itself.
      - name: Re-add git version control to code
        run: Rename-Item ._git .git

      # Run gitlint. Skip during PR runs, since PR commit messages are transient and usually full of gitlint violations.
      # PRs get squashed and get a proper commit message during merge.
      - name: Gitlint check
        run: gitlint --debug
        if: ${{ github.event_name	!= 'pull_request' }}
